# -*- coding: utf-8 -*-
"""Color quantization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xd7uiqe6HtqrKzNIh0bjSulwODqzA0C

#Importing all the necessary libraries
**#Overall steps involved are:**
1. Reading the image as 3d array .
2. Reshaping it into 2d array.
3. Using kmeans to find the required number of color clusters in the image.
4. Rounding the centers of all the clusters.
5. Using the model to predict which points lie in which cluster.
6. Reshaping the array in order to view it as an image .
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img_arr_3d= mpimg.imread('palm_trees.jpg')

img_arr_3d.shape

plt.imshow(img_arr_3d)

h,w,c=img_arr_3d.shape

# converting form 3d to 2d
img_arr_2d=img_arr_3d.reshape(h*w,c)

"""# Using Kmeans clustering"""

from sklearn.cluster import KMeans
model=KMeans(n_clusters=5)
labels=model.fit_predict(img_arr_2d)

rgb_codes=model.cluster_centers_.round(0).astype('int')

p=rgb_codes[labels]

final=np.reshape(p,(h,w,c))

"""#Output of given number of colors in the final image separately"""

plt.imshow(final)